# Generated by Django 5.2 on 2025-05-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_accessory_remove_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
