# Generated by Django 5.2 on 2025-05-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_accessories_fashions_foods_furnitures_homeaccesories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Fashions',
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
        migrations.DeleteModel(
            name='Furnitures',
        ),
        migrations.DeleteModel(
            name='HomeAccesories',
        ),
    ]
