# Generated by Django 5.2 on 2025-05-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_product_categories_product_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
