# Generated by Django 5.2 on 2025-05-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
    ]
